"""Render the latest judge-facing report from committed run artifacts.

This module is intentionally a renderer, not a second scoring engine. Numbers are copied
from the append-only history files or from captured command output. If an artifact does not
contain a value, the report leaves it out.
"""

from __future__ import annotations

import argparse
import datetime as dt
import json
import re
from pathlib import Path
from typing import Any, Iterable

from twin import evidence
from twin.target import load_target


def _records(path: Path) -> list[dict[str, Any]]:
    if not path.exists():
        return []
    records = []
    for line in path.read_text().splitlines():
        try:
            value = json.loads(line)
        except json.JSONDecodeError:
            continue
        if isinstance(value, dict):
            records.append(value)
    return records


def _timestamp(record: dict[str, Any], *fields: str) -> dt.datetime:
    for field in fields:
        value = record.get(field)
        if value:
            try:
                return dt.datetime.fromisoformat(str(value).replace("Z", "+00:00"))
            except ValueError:
                pass
    return dt.datetime.min.replace(tzinfo=dt.timezone.utc)


def _instant(value: Any) -> dt.datetime | None:
    """One timestamp as a comparable instant, or None if it does not parse.

    Headers and history lines both carry UTC, but one writes `Z` and the other a numeric
    offset. Compared as text those sort against each other incorrectly; compared as instants
    they do not.
    """
    if not value:
        return None
    try:
        parsed = dt.datetime.fromisoformat(str(value).replace("Z", "+00:00"))
    except ValueError:
        return None
    return parsed if parsed.tzinfo else parsed.replace(tzinfo=dt.timezone.utc)


def _latest(records: list[dict[str, Any]], *fields: str) -> dict[str, Any] | None:
    return max(records, key=lambda record: _timestamp(record, *fields), default=None)


def _display(path: Path, root: Path) -> str:
    try:
        return path.relative_to(root).as_posix()
    except ValueError:
        return path.as_posix()


def _fenced(title: str, source: Path, root: Path, text: str) -> str:
    return f"# {title}\n\nSource artifact: `{_display(source, root)}`.\n\n```text\n{text.rstrip()}\n```\n"


def _verification_artifact(
    root: Path, target: str, report_date: str, record: dict | None = None
) -> Path:
    """The verification capture that belongs to this run of this estate.

    Preference order is strongest evidence first: the capture the reported run named for
    itself, then this estate's capture from the reported date, then its most recent nightly
    capture, then the standing example the target names for itself. Nothing here falls back
    to another estate's output — a verification result filed under the wrong estate is worse
    than none, because it looks like evidence.

    The recorded name is preferred because a date can hold more than one capture, and a later
    run that produced a capture but then failed appends no history. Choosing the newest file
    on the date would hand that failed run's evidence to the successful record above it —
    which is the provenance error the run-stamped filenames exist to prevent. Only records
    predating that field fall through to date discovery.
    """
    directory = root / evidence.VERIFICATION

    # A record that names its capture is answered by that capture or by nothing. Falling
    # through to discovery here would let a damaged history line pick up another run's
    # evidence, which is the failure this resolution order exists to prevent — and a report
    # that cannot find the evidence it points at should stop rather than substitute.
    named = (record or {}).get("verification_artifact")
    if named:
        candidate = root / str(named)
        if not (candidate.exists() and candidate.parent == directory and target in candidate.name):
            raise FileNotFoundError(
                f"history names a verification artifact that does not resolve for {target}: "
                f"{named}"
            )
        return candidate

    def generated_at(path: Path) -> str:
        # \S rather than [^ ]: the latter does not exclude newlines, so a header whose
        # timestamp ends the line captured the following line with it.
        match = re.search(r"generated by .*? at (\S+)", path.read_text()[:500])
        return match.group(1) if match else ""

    # A capture generated after the run being reported cannot be that run's evidence. Older
    # history lines predate the recorded-name field, so they still discover by date — but a
    # later capture must not be swept up by that discovery. Compared as instants, because
    # equivalent timestamps can be written with a Z or a numeric offset and only one of those
    # pairs sorts correctly as text.
    ceiling = _instant((record or {}).get("read_at") or (record or {}).get("scored_at"))

    def not_after_the_run(path: Path) -> bool:
        stamp = _instant(generated_at(path))
        return not (ceiling and stamp and stamp > ceiling)

    on_date = [
        path
        for path in evidence.verification_artifacts_on(target, report_date, root)
        if not_after_the_run(path)
    ]
    if on_date:
        return max(on_date, key=lambda path: (generated_at(path), path.name))

    nightly = [p for p in sorted(directory.glob(f"nightly-{target}-*.txt")) if not_after_the_run(p)]
    if nightly:
        return max(nightly, key=lambda path: (generated_at(path), path.name))

    example = load_target(target).verification_example
    if example is not None and Path(example).exists():
        return Path(example)
    raise FileNotFoundError(
        f"no verification artifact for {target}; expected one under "
        f"{directory}/nightly-{target}-{report_date}*.txt or a "
        f"verification_example in targets/{target}.yml"
    )


def _json_block(title: str, record: dict[str, Any] | None, source: Path, root: Path) -> str:
    if record is None:
        return f"## {title}\n\nNo record was present in `{_display(source, root)}`.\n\n"
    return (
        f"## {title}\n\nSource artifact: `{_display(source, root)}`.\n\n"
        "```json\n"
        f"{json.dumps(record, indent=2, sort_keys=True)}\n"
        "```\n\n"
    )


def _missed_since(
    attempts: list[dict[str, Any]],
    verified_at: dict[str, dt.datetime],
    newest_verified: dt.datetime,
) -> list[dict[str, Any]]:
    """Attempts that failed after the run this report shows, newest first.

    Each attempt is judged against its own estate's latest verified run: a commerce failure
    says nothing about whether the operations numbers are current, and collapsing the two
    would either hide a real gap or invent one. An attempt that died before it chose a target
    is judged against the newest verified run of any estate, because it may have prevented
    all of them.
    """
    failed = []
    for attempt in attempts:
        if attempt.get("status") == "succeeded":
            continue
        target = attempt.get("target")
        cutoff = verified_at.get(target, newest_verified) if target else newest_verified
        if _timestamp(attempt, "attempted_at") > cutoff:
            failed.append(attempt)
    return sorted(failed, key=lambda attempt: _timestamp(attempt, "attempted_at"), reverse=True)


def _missed_section(missed: list[dict[str, Any]], source: Path, root: Path) -> list[str]:
    if not missed:
        return []
    lines = [
        "## Runs that did not complete",
        "",
        "These runs were attempted and failed. They appended no estate read and no score, so "
        "nothing above reflects them — they are listed because a success-only history cannot "
        "distinguish a failed night from a night nobody ran.",
        "",
        f"Source artifact: `{_display(source, root)}`.",
        "",
        "| attempted (UTC) | estate | stage reached | commit | detail |",
        "|---|---|---|---|---|",
    ]
    for attempt in missed:
        commit = attempt.get("commit") or "—"
        if attempt.get("dirty"):
            commit += " (dirty)"
        detail = str(attempt.get("detail") or "—")
        if attempt.get("reconstructed_from"):
            detail += f" — reconstructed from `{attempt['reconstructed_from']}`"
        lines.append(
            f"| {attempt.get('attempted_at') or '—'} | {attempt.get('target') or '—'} "
            f"| {attempt.get('stage') or '—'} | `{commit}` | {detail} |"
        )
    lines.append("")
    return lines


def _render_target(root: Path, target: str) -> dict[str, Any] | None:
    """Write one estate's dated evidence bundle and return what the index needs.

    Returns ``None`` when the estate has no history yet, which is an ordinary state for a
    target configured but not yet run — not an error, and not something to invent a bundle for.
    """
    read_source = evidence.nightly_history(target, root)
    score_source = evidence.fragility_history(target, root)
    read_record = _latest(_records(read_source), "read_at")
    score_record = _latest(_records(score_source), "scored_at")
    if read_record is None and score_record is None:
        return None

    dated_record = read_record or score_record
    verified_at = _timestamp(dated_record, "read_at", "scored_at")
    report_date = verified_at.date().isoformat()
    output_dir = root / "reports" / "nightly" / report_date / target
    output_dir.mkdir(parents=True, exist_ok=True)

    captured = evidence.captured_dir(target, root)
    scorecard_source = captured / "fragility-scorecard.txt"
    mcp_source = captured / "estate-graph.txt"
    for source in (scorecard_source, mcp_source):
        if not source.exists():
            raise FileNotFoundError(f"required generated artifact is missing: {source}")
    verification_source = _verification_artifact(root, target, report_date, dated_record)

    (output_dir / "scorecard.md").write_text(
        _fenced("Fragility scorecard", scorecard_source, root, scorecard_source.read_text())
    )
    (output_dir / "verification.md").write_text(
        _fenced("Verification result", verification_source, root, verification_source.read_text())
    )
    (output_dir / "mcp-readback.md").write_text(
        _fenced("MCP readback", mcp_source, root, mcp_source.read_text())
    )
    (output_dir / "estate-fingerprint.md").write_text(
        "# Estate fingerprint\n\n"
        "The records below are copied from the append-only history artifacts.\n\n"
        + _json_block("Latest estate read", read_record, read_source, root)
        + _json_block("Latest fragility score", score_record, score_source, root)
    )
    return {
        "target": target,
        "report_date": report_date,
        "verified_at": verified_at,
        "read_record": read_record,
        "read_source": read_source,
        "score_source": score_source,
    }


def _target_section(summary: dict[str, Any], root: Path, missed_count: int) -> list[str]:
    target, report_date = summary["target"], summary["report_date"]
    read_record = summary["read_record"]
    base = f"nightly/{report_date}/{target}"
    lines = [
        f"## {target}",
        "",
        f"Run artifacts: [`reports/{base}/`](" + base + "/)",
        "",
    ]
    if missed_count:
        lines.extend(
            [
                f"**{missed_count} later {target} run(s) did not complete.** The numbers below "
                "are therefore older than the most recent attempt; see "
                "[runs that did not complete](#runs-that-did-not-complete).",
                "",
            ]
        )
    facts = []
    if read_record and read_record.get("pipeline_status") is not None:
        facts.append(f"Pipeline status: `{read_record['pipeline_status']}`")
    for label, key in (
        ("Tests passed", "tests_passed"),
        ("Verification precision", "verification_precision"),
        ("Verification recall", "verification_recall"),
    ):
        if read_record and read_record.get(key) is not None:
            facts.append(f"{label}: `{read_record[key]}`")
    if facts:
        lines.extend([*facts, ""])
    lines.extend(
        [
            "| Evidence | Generated artifact |",
            "|---|---|",
            f"| Scorecard | [scorecard]({base}/scorecard.md) |",
            f"| Verification result | [verification]({base}/verification.md) |",
            f"| MCP readback | [MCP readback]({base}/mcp-readback.md) |",
            f"| Estate fingerprint | [fingerprint]({base}/estate-fingerprint.md) |",
            "",
            f"History source: `{_display(summary['read_source'], root)}` and "
            f"`{_display(summary['score_source'], root)}`.",
            "",
        ]
    )
    return lines


def render(root: Path = Path(".")) -> Path:
    """Write every estate's dated report and the stable ``reports/LATEST.md`` index."""
    root = root.resolve()
    targets = evidence.known_targets(root)
    summaries = [s for s in (_render_target(root, target) for target in targets) if s]
    if not summaries:
        raise FileNotFoundError("no nightly or fragility history records are available")

    attempt_source = evidence.attempts_history(root)
    attempts = _records(attempt_source)
    verified_at = {s["target"]: s["verified_at"] for s in summaries}
    newest_verified = max(verified_at.values())
    missed = _missed_since(attempts, verified_at, newest_verified)
    missed_by_target: dict[str, int] = {}
    for attempt in missed:
        missed_by_target[attempt.get("target") or ""] = (
            missed_by_target.get(attempt.get("target") or "", 0) + 1
        )

    latest_lines = [
        "# Twin — latest verified run",
        "",
        "This page is generated from captured outputs and append-only history; it is not a second computation of the score.",
        "",
        "Each estate is reported separately. Fragility scores are positions within an estate,",
        "so two estates' numbers are not comparable and are never combined here.",
        "",
    ]
    for summary in summaries:
        latest_lines.extend(
            _target_section(summary, root, missed_by_target.get(summary["target"], 0))
        )
    latest_lines.extend(_missed_section(missed, attempt_source, root))
    latest = root / "reports" / "LATEST.md"
    latest.parent.mkdir(parents=True, exist_ok=True)
    latest.write_text("\n".join(latest_lines))
    return latest


def main(argv: Iterable[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path("."))
    args = parser.parse_args(list(argv) if argv is not None else None)
    try:
        print(render(args.root))
    except (FileNotFoundError, OSError, ValueError) as exc:
        print(f"cannot render report: {exc}")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
