"""Render the latest judge-facing report from committed run artifacts.

This module is intentionally a renderer, not a second scoring engine. Numbers are copied
from the append-only history files or from captured command output. If an artifact does not
contain a value, the report leaves it out.
"""

from __future__ import annotations

import argparse
import datetime as dt
import json
import re
from pathlib import Path
from typing import Any, Iterable


def _records(path: Path) -> list[dict[str, Any]]:
    if not path.exists():
        return []
    records = []
    for line in path.read_text().splitlines():
        try:
            value = json.loads(line)
        except json.JSONDecodeError:
            continue
        if isinstance(value, dict):
            records.append(value)
    return records


def _timestamp(record: dict[str, Any], *fields: str) -> dt.datetime:
    for field in fields:
        value = record.get(field)
        if value:
            try:
                return dt.datetime.fromisoformat(str(value).replace("Z", "+00:00"))
            except ValueError:
                pass
    return dt.datetime.min.replace(tzinfo=dt.timezone.utc)


def _latest(records: list[dict[str, Any]], *fields: str) -> dict[str, Any] | None:
    return max(records, key=lambda record: _timestamp(record, *fields), default=None)


def _display(path: Path, root: Path) -> str:
    try:
        return path.relative_to(root).as_posix()
    except ValueError:
        return path.as_posix()


def _fenced(title: str, source: Path, root: Path, text: str) -> str:
    return f"# {title}\n\nSource artifact: `{_display(source, root)}`.\n\n```text\n{text.rstrip()}\n```\n"


def _verification_artifact(root: Path, report_date: str) -> Path:
    directory = root / "examples" / "verification"
    dated = directory / f"nightly-{report_date}.txt"
    if dated.exists():
        return dated
    candidates = sorted(directory.glob("*.txt"))
    if not candidates:
        raise FileNotFoundError(f"no verification artifacts under {directory}")

    def generated_at(path: Path) -> str:
        match = re.search(r"generated by .*? at ([^ ]+)", path.read_text()[:500])
        return match.group(1) if match else ""

    preferred = directory / "merchant_id_nulled_at_source.txt"
    if preferred.exists():
        return preferred
    return max(candidates, key=lambda path: (generated_at(path), path.name))


def _json_block(title: str, record: dict[str, Any] | None, source: Path, root: Path) -> str:
    if record is None:
        return f"## {title}\n\nNo record was present in `{_display(source, root)}`.\n\n"
    return (
        f"## {title}\n\nSource artifact: `{_display(source, root)}`.\n\n"
        "```json\n"
        f"{json.dumps(record, indent=2, sort_keys=True)}\n"
        "```\n\n"
    )


def render(root: Path = Path(".")) -> Path:
    """Write the dated report and the stable ``reports/LATEST.md`` link target."""
    root = root.resolve()
    history_dir = root / "examples" / "history"
    read_source = history_dir / "nightly.jsonl"
    score_source = history_dir / "fragility.jsonl"
    read_record = _latest(_records(read_source), "read_at")
    score_record = _latest(_records(score_source), "scored_at")
    if read_record is None and score_record is None:
        raise FileNotFoundError("no nightly or fragility history records are available")

    dated_record = read_record or score_record
    report_date = _timestamp(dated_record, "read_at", "scored_at").date().isoformat()
    output_dir = root / "reports" / "nightly" / report_date
    output_dir.mkdir(parents=True, exist_ok=True)

    scorecard_source = root / "examples" / "reports" / "fragility-scorecard.txt"
    mcp_source = root / "examples" / "reports" / "estate-graph.txt"
    for source in (scorecard_source, mcp_source):
        if not source.exists():
            raise FileNotFoundError(f"required generated artifact is missing: {source}")
    verification_source = _verification_artifact(root, report_date)

    (output_dir / "scorecard.md").write_text(
        _fenced("Fragility scorecard", scorecard_source, root, scorecard_source.read_text())
    )
    (output_dir / "verification.md").write_text(
        _fenced("Verification result", verification_source, root, verification_source.read_text())
    )
    (output_dir / "mcp-readback.md").write_text(
        _fenced("MCP readback", mcp_source, root, mcp_source.read_text())
    )
    (output_dir / "estate-fingerprint.md").write_text(
        "# Estate fingerprint\n\n"
        "The records below are copied from the append-only history artifacts.\n\n"
        + _json_block("Latest estate read", read_record, read_source, root)
        + _json_block("Latest fragility score", score_record, score_source, root)
    )

    latest_lines = [
        "# Twin — latest verified run",
        "",
        "This page is generated from captured outputs and append-only history; it is not a second computation of the score.",
        "",
        f"Run artifacts: [`reports/nightly/{report_date}/`](nightly/{report_date}/)",
        "",
    ]
    if read_record and read_record.get("pipeline_status") is not None:
        latest_lines.extend([f"Pipeline status: `{read_record['pipeline_status']}`", ""])
    for label, key in (
        ("Tests passed", "tests_passed"),
        ("Verification precision", "verification_precision"),
        ("Verification recall", "verification_recall"),
    ):
        if read_record and read_record.get(key) is not None:
            latest_lines.append(f"{label}: `{read_record[key]}`")
    if any(line.startswith(("Tests passed:", "Verification precision:", "Verification recall:")) for line in latest_lines):
        latest_lines.append("")
    latest_lines.extend(
        [
            "| Evidence | Generated artifact |",
            "|---|---|",
            "| Scorecard | [scorecard](nightly/" + report_date + "/scorecard.md) |",
            "| Verification result | [verification](nightly/" + report_date + "/verification.md) |",
            "| MCP readback | [MCP readback](nightly/" + report_date + "/mcp-readback.md) |",
            "| Estate fingerprint | [fingerprint](nightly/" + report_date + "/estate-fingerprint.md) |",
            "",
            f"History source: `{read_source.relative_to(root).as_posix()}` and `{score_source.relative_to(root).as_posix()}`.",
            "",
        ]
    )
    latest = root / "reports" / "LATEST.md"
    latest.parent.mkdir(parents=True, exist_ok=True)
    latest.write_text("\n".join(latest_lines))
    return latest


def main(argv: Iterable[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path("."))
    args = parser.parse_args(list(argv) if argv is not None else None)
    try:
        print(render(args.root))
    except (FileNotFoundError, OSError, ValueError) as exc:
        print(f"cannot render report: {exc}")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
