#!/usr/bin/env bash
#
# Regenerate everything in examples/ from real runs against a live stack.
#
# The artifacts in examples/ exist so that a reader can see what Twin produces without
# running it, and the only way that is worth anything is if nobody ever edits them by hand.
# This script is how they are made: every file it writes is the stdout of a command that
# actually executed against the estate, captured verbatim.
#
# It is deliberately not part of the nightly. The nightly appends history, which is a claim
# about change over time and must accumulate; these are snapshots of the current commit, and
# regenerating them on a schedule would churn the diff for no evidential gain.
#
# Usage:  make examples          (stack must already be up, estate already built)
#
# Anything that fails leaves the previous artifact in place rather than truncating it to a
# half-written file, because a stale artifact that says where it came from is more honest
# than a fresh one that stops mid-sentence.

set -euo pipefail

cd "$(dirname "$0")/.."

OUT="examples"
STAMP="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
COMMIT="$(git rev-parse --short HEAD)"
FAILURES=0

# Captured output is read as evidence, so each file says what produced it and when. Twin's
# own reports carry a graph fingerprint; this header carries the things the report cannot
# know about itself — which commit was checked out, and when it ran.
header() {
	printf '# %s\n# generated by ops/capture-examples.sh at %s from commit %s\n# regenerate with: make examples\n\n' \
		"$1" "$STAMP" "$COMMIT"
}

# Capture a command into a file, but only overwrite on success. Terminal escapes are stripped
# because these are read in a browser on GitHub, not in a terminal.
capture() {
	local dest="$1" title="$2"
	shift 2
	local tmp status=0
	tmp="$(mktemp)"
	printf '  %-52s' "$dest"

	# The command's own exit status, not the last filter's. `set -e` is disabled for this
	# one line so that a command which legitimately fails is reported by this script rather
	# than killing the whole capture.
	set +e
	{
		header "$title"
		# Terminal escapes go because these are read on GitHub, not in a terminal. The
		# `Container twin-... Created` lines go because they are docker compose talking
		# about itself: they change every run, which would churn the diff, and they say
		# nothing about the estate.
		"$@" 2>&1 |
			sed -E 's/\x1b\[[0-9;]*[mGKHF]//g' |
			grep -vE '^ (Container|Network|Volume) ' |
			cat -s
		status="${PIPESTATUS[0]}"
	} >"$tmp"
	set -e

	if [ "$status" -eq 0 ]; then
		# mktemp makes files 0600; these are committed and read by everyone.
		chmod 644 "$tmp"
		mv "$tmp" "$dest"
		printf 'ok\n'
		return 0
	fi

	# A failed command's output is not evidence of anything, so it is not written. The
	# previous artifact stays as it was and the reason is printed here.
	rm -f "$tmp"
	printf 'FAILED (exit %s), previous kept\n' "$status"
	FAILURES=$((FAILURES + 1))
	return 0
}

mkdir -p "$OUT/reports" "$OUT/verification" "$OUT/incidents"

echo "Capturing examples/ from live runs. About seven minutes with the estate already built."
echo

echo "Estate and scoring:"
capture "$OUT/reports/verify-estate.txt" \
	"The demo estate, checked against DataHub" \
	make --no-print-directory verify-estate
capture "$OUT/reports/fragility-scorecard.txt" \
	"Fragility ranking across the whole estate" \
	make --no-print-directory score
capture "$OUT/reports/estate-graph.txt" \
	"The estate graph as Stage 1 read it over MCP" \
	make --no-print-directory graph
echo

echo "Scenarios, each run end to end and graded:"
for scenario in scenarios/*.yml; do
	name="$(basename "$scenario" .yml)"
	capture "$OUT/verification/$name.txt" \
		"$name — predicted, executed for real, and graded" \
		make --no-print-directory run "SCENARIO=$scenario"
done
echo

echo "Capturing one real incident run, then removing Twin's catalog state:"
capture "$OUT/incidents/fx_rate_column_drop.txt" \
	"fx_rate_column_drop — incidents raised for observed failures" \
	make --no-print-directory incidents "SCENARIO=scenarios/fx_rate_column_drop.yml"
make --no-print-directory unwrite
echo

# Not captured through header(): this one is markdown, and it writes its own provenance.
echo "Rendering the nightly trend:"
printf '  %-52s' "$OUT/history/README.md"
python3 ops/render-history.py >"$OUT/history/README.md"
printf 'ok\n'
echo

if [ "$FAILURES" -gt 0 ]; then
	echo "Done, with $FAILURES failure(s) above. Those artifacts were not rewritten."
	echo "A failed command is not evidence, so its previous artifact was kept."
	exit 1
fi

echo "Done. Every file above is captured stdout from a command that really ran."
