#!/usr/bin/env bash
#
# The nightly read, run from a host cron rather than from CI.
#
# Twin's fragility trend is a claim about change over time, and it is only worth anything if
# the runs actually happened — accumulated history cannot be manufactured later. The GitHub
# Actions workflow in .github/workflows/twin-nightly.yml does this job on a runner that
# builds the estate from nothing. This script does the same job against a host where the
# stack is already up, which is the right shape for a machine that runs Twin continuously.
#
# Either path appends to the same append-only file. A line is written only when a read
# genuinely succeeded, and the estate is verified first, so a broken estate produces no
# history rather than a line asserting something that was not checked.
#
# Direct invocation is the VPS cron mode: it commits and pushes after a successful run.
# `make nightly` sets NIGHTLY_AUTOCOMMIT=0 so a Mac or another operator can inspect the
# generated evidence and commit it with their normal Git credentials.
#
# Install on the VPS:
#   crontab -e
#   17 3 * * * /root/twin/ops/nightly-read.sh >> /var/log/twin-nightly.log 2>&1

set -euo pipefail

cd "$(dirname "$0")/.."

# cron runs with a minimal environment. git needs HOME to find the credential helper that
# gh installed, and docker compose needs a PATH that includes it.
export HOME="${HOME:-/root}"
export PATH="/opt/homebrew/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:${PATH:-}"

NIGHTLY_AUTOCOMMIT="${NIGHTLY_AUTOCOMMIT:-1}"
if [ "$NIGHTLY_AUTOCOMMIT" != "0" ] && [ "$NIGHTLY_AUTOCOMMIT" != "1" ]; then
  echo "NIGHTLY_AUTOCOMMIT must be 0 or 1" >&2
  exit 2
fi

HISTORY="examples/history/nightly.jsonl"
SCORES="examples/history/fragility.jsonl"
RUN_DATE="$(date -u +%Y-%m-%d)"
VERIFICATION_ARTIFACT="examples/verification/nightly-${RUN_DATE}.txt"
RUN_REPORT_DIR="examples/reports/nightly/${RUN_DATE}"
MCP_ARTIFACT="$RUN_REPORT_DIR/estate-graph.txt"
SCORE_ARTIFACT="$RUN_REPORT_DIR/fragility-scorecard.txt"
TMP_DIR="$(mktemp -d)"
trap 'rm -rf "$TMP_DIR"' EXIT

say() { printf '[%s] %s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$1"; }

clean_capture() {
  # Compose progress lines can contain trailing spaces. Strip those and trailing blank
  # lines so generated evidence also passes the repository whitespace gate.
  awk '
    { sub(/[[:space:]]+$/, ""); lines[NR] = $0; if ($0 != "") last = NR }
    END { for (line = 1; line <= last; line++) print lines[line] }
  ' "$1" > "$1.clean"
  mv "$1.clean" "$1"
}

say "starting nightly read"

# The stack is expected to be up already. Bring up anything that is not, rather than
# assuming: a container restarted by the host would otherwise fail the read at 03:17 with
# nobody watching.
docker compose up -d --wait warehouse datahub-gms datahub-frontend

say "verifying the estate"
docker compose run --rm -T twin python -m estate.verify_estate

say "running the source-column verification"
VERIFICATION_TMP="$TMP_DIR/verification.txt"
{
  printf '# nightly source-column verification\n# generated by ops/nightly-read.sh at %s from commit %s\n# source: make run TARGET=commerce SCENARIO=scenarios/merchant_id_nulled_at_source.yml\n\n' \
    "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$(git rev-parse --short HEAD)"
  docker compose run --rm -T twin python -m twin.run --target commerce \
    scenarios/merchant_id_nulled_at_source.yml
} 2>&1 | tee "$VERIFICATION_TMP"
clean_capture "$VERIFICATION_TMP"
mv "$VERIFICATION_TMP" "$VERIFICATION_ARTIFACT"

TEST_LOG="$TMP_DIR/pytest.txt"
say "running the test suite"
# pyproject.toml already supplies one -q. Passing another here raises pytest's quiet
# level to -qq, which suppresses the final "N passed" line this evidence parser reads.
docker compose run --rm -T twin python -m pytest 2>&1 | tee "$TEST_LOG"
TESTS_PASSED="$(sed -nE 's/^([0-9]+) passed([ ,].*)?$/\1/p' "$TEST_LOG" | tail -1)"
if [ -z "$TESTS_PASSED" ]; then
  say "could not find the pytest passed count"
  exit 1
fi

read -r VERIFICATION_PRECISION VERIFICATION_RECALL < <(
  sed -nE 's/.*predicted [0-9]+ .* precision ([0-9.]+)   recall ([0-9.]+).*/\1 \2/p' \
    "$VERIFICATION_ARTIFACT" | tail -1
)
if [ -z "${VERIFICATION_PRECISION:-}" ] || [ -z "${VERIFICATION_RECALL:-}" ]; then
  say "could not find precision and recall in the actual verification result"
  exit 1
fi

say "reading the estate over MCP"
MCP_TMP="$TMP_DIR/estate-graph.txt"
{
  printf '# nightly MCP estate read\n# generated by ops/nightly-read.sh at %s from commit %s\n\n' \
    "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$(git rev-parse --short HEAD)"
  docker compose run --rm -T twin python -m twin.read
} 2>&1 | tee "$MCP_TMP"
clean_capture "$MCP_TMP"
mkdir -p "$RUN_REPORT_DIR"
mv "$MCP_TMP" "$MCP_ARTIFACT"

say "scoring fragility"
SCORE_TMP="$TMP_DIR/fragility-scorecard.txt"
{
  printf '# nightly fragility scorecard\n# generated by ops/nightly-read.sh at %s from commit %s\n\n' \
    "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$(git rev-parse --short HEAD)"
  docker compose run --rm -T twin python -m twin.score --append-history "$SCORES"
} 2>&1 | tee "$SCORE_TMP"
clean_capture "$SCORE_TMP"
mv "$SCORE_TMP" "$SCORE_ARTIFACT"

say "writing fragility scores back to DataHub"
docker compose run --rm -T twin python -m twin.write

say "recording the successful nightly run"
docker compose run --rm -T twin python -m twin.read --target commerce --cached \
  --append-history "$HISTORY" \
  --tests-passed "$TESTS_PASSED" \
  --verification-precision "$VERIFICATION_PRECISION" \
  --verification-recall "$VERIFICATION_RECALL" \
  --pipeline-status succeeded \
  --verification-artifact "$VERIFICATION_ARTIFACT"

say "rendering the judge-facing report"
make --no-print-directory report

if git diff --quiet -- "$HISTORY" "$SCORES"; then
  say "no new history line; the read must have failed"
  exit 1
fi

if [ "$NIGHTLY_AUTOCOMMIT" = "0" ]; then
  say "evidence generated; commit reports/, examples/history/, examples/reports/ and examples/verification/ when reviewed"
  exit 0
fi

git config user.name jennycruzy
git config user.email jennycruzy@users.noreply.github.com
git add "$HISTORY" "$SCORES" "$VERIFICATION_ARTIFACT" "$RUN_REPORT_DIR" reports
git commit -q -m "Record the nightly estate read for $(date -u +%Y-%m-%d)"
git push -q origin main

say "recorded and pushed"
